version: "3.4"

services:
  django:
    build: .
    ports:
      - "8080:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=Test1234
      - DB_HOST=db
      - DB_PORT=5432
      - LC_CTYPE=C.UTF-8
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
    depends_on:
      - db
  db:
    image: postgres:11.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Test1234
